export const BROWSER_CONFIG = {
	headless: false,
	args: [
		"--disable-blink-features=AutomationControlled",
		"--no-sandbox",
		"--disable-gpu",
		"--disable-dev-shm-usage",
		"--disable-backgrounding-occluded-windows",
		"--disable-web-security",
		"--disable-features=VizDisplayCompositor",
		"--disable-extensions",
		"--disable-plugins",
		"--disable-images",
		"--disable-javascript-harmony-shipping",
		"--disable-background-timer-throttling",
		"--disable-renderer-backgrounding",
		"--disable-field-trial-config",
		"--disable-ipc-flooding-protection",
		"--no-first-run",
		"--no-default-browser-check",
		"--no-pings",
		"--password-store=basic",
		"--use-mock-keychain",
		"--disable-component-extensions-with-background-pages",
		"--disable-default-apps",
		"--mute-audio",
		"--disable-sync",
		"--disable-translate",
		"--disable-background-networking",
		"--disable-background-downloads",
		"--disable-add-to-shelf",
		"--disable-client-side-phishing-detection",
		"--disable-component-update",
		"--disable-default-apps",
		"--disable-domain-reliability",
		"--disable-features=TranslateUI",
		"--disable-hang-monitor",
		"--disable-prompt-on-repost",
		"--disable-web-resources",
		"--aggressive-cache-discard",
		"--memory-pressure-off",
		"--max_old_space_size=4096",
	],
};

export const CONTEXT_CONFIG = {
	locale: Intl.DateTimeFormat().resolvedOptions().locale,
	timezoneId: Intl.DateTimeFormat().resolvedOptions().timeZone,
	userAgent:
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115 Safari/537.36",
	viewport: { width: 200, height: 200 },
	javaScriptEnabled: true,
	reducedMotion: "reduce" as const,
	forcedColors: "none" as const,
	colorScheme: "no-preference" as const,
	extraHTTPHeaders: {
		"Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
		"Accept-Encoding": "gzip, deflate, br",
		Accept:
			"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
		"Cache-Control": "no-cache",
		Pragma: "no-cache",
	},
};
