/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as IndexRouteImport } from './routes/index'

const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estudiantes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estudiantes'
  id: '__root__' | '/' | '/estudiantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudiantesRoute: typeof EstudiantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudiantesRoute: EstudiantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
