/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstudiantesLoginRouteImport } from './routes/estudiantes_.login'
import { Route as EstudiantesHorarioRouteImport } from './routes/estudiantes_.horario'
import { Route as EstudiantesCalificacionesRouteImport } from './routes/estudiantes_.calificaciones'

const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesLoginRoute = EstudiantesLoginRouteImport.update({
  id: '/estudiantes_/login',
  path: '/estudiantes/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesHorarioRoute = EstudiantesHorarioRouteImport.update({
  id: '/estudiantes_/horario',
  path: '/estudiantes/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesCalificacionesRoute =
  EstudiantesCalificacionesRouteImport.update({
    id: '/estudiantes_/calificaciones',
    path: '/estudiantes/calificaciones',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/estudiantes/calificaciones': typeof EstudiantesCalificacionesRoute
  '/estudiantes/horario': typeof EstudiantesHorarioRoute
  '/estudiantes/login': typeof EstudiantesLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/estudiantes/calificaciones': typeof EstudiantesCalificacionesRoute
  '/estudiantes/horario': typeof EstudiantesHorarioRoute
  '/estudiantes/login': typeof EstudiantesLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/estudiantes_/calificaciones': typeof EstudiantesCalificacionesRoute
  '/estudiantes_/horario': typeof EstudiantesHorarioRoute
  '/estudiantes_/login': typeof EstudiantesLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estudiantes'
    | '/estudiantes/calificaciones'
    | '/estudiantes/horario'
    | '/estudiantes/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estudiantes'
    | '/estudiantes/calificaciones'
    | '/estudiantes/horario'
    | '/estudiantes/login'
  id:
    | '__root__'
    | '/'
    | '/estudiantes'
    | '/estudiantes_/calificaciones'
    | '/estudiantes_/horario'
    | '/estudiantes_/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudiantesRoute: typeof EstudiantesRoute
  EstudiantesCalificacionesRoute: typeof EstudiantesCalificacionesRoute
  EstudiantesHorarioRoute: typeof EstudiantesHorarioRoute
  EstudiantesLoginRoute: typeof EstudiantesLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes_/login': {
      id: '/estudiantes_/login'
      path: '/estudiantes/login'
      fullPath: '/estudiantes/login'
      preLoaderRoute: typeof EstudiantesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes_/horario': {
      id: '/estudiantes_/horario'
      path: '/estudiantes/horario'
      fullPath: '/estudiantes/horario'
      preLoaderRoute: typeof EstudiantesHorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes_/calificaciones': {
      id: '/estudiantes_/calificaciones'
      path: '/estudiantes/calificaciones'
      fullPath: '/estudiantes/calificaciones'
      preLoaderRoute: typeof EstudiantesCalificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudiantesRoute: EstudiantesRoute,
  EstudiantesCalificacionesRoute: EstudiantesCalificacionesRoute,
  EstudiantesHorarioRoute: EstudiantesHorarioRoute,
  EstudiantesLoginRoute: EstudiantesLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
