export const horario: Array<{
	id: number;
	materia: string;
	codigo: string;
	profesor: string;
	aula: string;
	dia: string;
	horaInicio: string;
	horaFin: string;
	tipo: string;
	color: string;
}> = [
	{
		id: 1,
		materia: "Programación Orientada a Objetos",
		codigo: "CSC-301",
		profesor: "Dr. García Martínez",
		aula: "Lab-A201",
		dia: "Lunes",
		horaInicio: "08:00",
		horaFin: "10:00",
		tipo: "Laboratorio",
		color: "bg-blue-500",
	},
	{
		id: 2,
		materia: "Base de Datos",
		codigo: "CSC-302",
		profesor: "Mtra. López Hernández",
		aula: "Aula-B105",
		dia: "Lunes",
		horaInicio: "10:00",
		horaFin: "12:00",
		tipo: "Teoría",
		color: "bg-green-500",
	},
	{
		id: 3,
		materia: "Taller de Desarrollo Web",
		codigo: "CSC-501",
		profesor: "Ing. Ramírez Torres",
		aula: "Lab-A301",
		dia: "Lunes",
		horaInicio: "14:00",
		horaFin: "17:00",
		tipo: "Taller",
		color: "bg-indigo-500",
	},
	{
		id: 4,
		materia: "Matemáticas Discretas",
		codigo: "MAT-201",
		profesor: "Dr. Rodríguez Silva",
		aula: "Aula-C301",
		dia: "Martes",
		horaInicio: "08:00",
		horaFin: "10:00",
		tipo: "Teoría",
		color: "bg-purple-500",
	},
	{
		id: 5,
		materia: "Ingeniería de Software",
		codigo: "CSC-401",
		profesor: "Ing. Morales Castro",
		aula: "Lab-A203",
		dia: "Martes",
		horaInicio: "14:00",
		horaFin: "16:00",
		tipo: "Laboratorio",
		color: "bg-orange-500",
	},
	{
		id: 6,
		materia: "Programación Orientada a Objetos",
		codigo: "CSC-301",
		profesor: "Dr. García Martínez",
		aula: "Aula-B102",
		dia: "Miércoles",
		horaInicio: "08:00",
		horaFin: "10:00",
		tipo: "Teoría",
		color: "bg-blue-500",
	},
	{
		id: 7,
		materia: "Base de Datos",
		codigo: "CSC-302",
		profesor: "Mtra. López Hernández",
		aula: "Lab-A204",
		dia: "Miércoles",
		horaInicio: "12:00",
		horaFin: "14:00",
		tipo: "Laboratorio",
		color: "bg-green-500",
	},
	{
		id: 8,
		materia: "Proyecto Integrador",
		codigo: "CSC-601",
		profesor: "Dr. Vázquez Mendoza",
		aula: "Lab-B301",
		dia: "Miércoles",
		horaInicio: "15:00",
		horaFin: "18:00",
		tipo: "Proyecto",
		color: "bg-red-500",
	},
	{
		id: 9,
		materia: "Matemáticas Discretas",
		codigo: "MAT-201",
		profesor: "Dr. Rodríguez Silva",
		aula: "Aula-C301",
		dia: "Jueves",
		horaInicio: "10:00",
		horaFin: "12:00",
		tipo: "Teoría",
		color: "bg-purple-500",
	},
	{
		id: 10,
		materia: "Ingeniería de Software",
		codigo: "CSC-401",
		profesor: "Ing. Morales Castro",
		aula: "Aula-B106",
		dia: "Viernes",
		horaInicio: "08:00",
		horaFin: "10:00",
		tipo: "Teoría",
		color: "bg-orange-500",
	},
];

export const dias = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"];
export const horas = [
	"08:00",
	"09:00",
	"10:00",
	"11:00",
	"12:00",
	"13:00",
	"14:00",
	"15:00",
	"16:00",
	"17:00",
	"18:00",
];
